name: Industrialisation continue sur le serveur AWS (Tomcat)
on: push
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: |
          jar cvf Fr0zenKFC_B2.war *
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.CAMION }}
        username: ${{ secrets.MOTO }}
        key: ${{ secrets.VOITURE }}
        port: ${{ secrets.VELO }}
        source: "Fr0zenKFC_B2.war"
        target: "/opt/tomcat/webapps"
